APP_LOCATIONS = { "Hyderabad" => ['Abids',
'AC Guards',
'Addagutta',
'Adikmet',
'Afzul Gunj',
'Ahmed Nagar',
'Airport',
'Akberbagh',
'Aliabad',
'Alwal',
'Amberpet',
'Ameerpet',
'Anandnagar Colony',
'Aramgarh',
'AS Rao Nagar',
'Asifnagar',
'Attapur',
'Ayodhyanagar',
'Ayyapa Colony',
'Azampura',
'Bagh Amberpet',
'Bagh Lingampally',
'Bahadupura',
'Balaji Nagar',
'Balanagar',
'Balapur Basthi',
'Balkampet',
'Banjara Hills',
'Banjara Hills Road No. 1',
'Banjara Hills Road No. 10',
'Banjara Hills Road No. 11',
'Banjara Hills Road No. 12',
'Banjara Hills Road No. 13',
'Banjara Hills Road No. 14',
'Banjara Hills Road No. 2',
'Banjara Hills Road No. 3',
'Banjara Hills Road No. 4',
'Banjara Hills Road No. 5',
'Banjara Hills Road No. 6',
'Banjara Hills Road No. 7',
'Banjara Hills Road No. 8',
'Banjara Hills Road No. 9',
'Banjara Nagar',
'Bansilalpet',
'Barkas',
'Barkatpura',
'Basheerbagh',
'Begum Bazar',
'Begumpet',
'Bhavani Nagar',
'Bholakpur',
'Bolarum ',
'Borabanda',
'Boudha Nagar',
'Bowenpally',
'Budha Nagar',
'Bus Station',
'Chakanwad',
'Champapet',
'Champapet',
'Chanda Nagar',
'Chandrayan gutta ',
'Charminar',
'Chavni',
'Cherlapalli',
'Chikadpally',
'Chilkalguda',
'Chintal',
'Chintala',
'Chintalbasti',
'City Center Mall Banjara',
'CRPF colony',
'Cyber Towers',
'Dabeerpura',
'Dattathreyanagar',
'Defence Colony',
'Devibagh',
'Dhoolpet',
'Dilsukhnagar',
'Domalguda',
'Doodbowli',
'Ecil',
'Erragadda',
'Errammanzil',
'Falaknuma',
'Fatehnagar',
'Fathe Darwaza',
'Gachibowli',
'Gaddi Annaram',
'Gajula Ramaram',
'Gandhinagar',
'Gandipet',
'Gaulipura',
'Gautham Nagar',
'Ghansi Bazar',
'Ghatkesar',
'Golconda Fort',
'Golnaka',
'Gosha Mahal',
'Gowliguda',
'Gowlipura',
'Green Lands',
'Gudimalkapur',
'Gunfoundry',
'Gurramguda',
'GVK one',
'Habsiguda',
'Hafeezpet',
'Hafeezpet',
'Hafiz Baba Nagar',
'Hayathnagar',
'Hillfort',
'Himayathnagar',
'Hitech City',
'Huda Colony',
'Hussain Alam',
'Hyderbad Central Mall',
'Hydernagar',
'I.S.Sadan',
'Ibrahimpatnam',
'Indirammanagar',
'Inorbit Mall',
'Ismail Nagar',
'Jagadgiri gutta',
'Jahanuma',
'Jairamnagar',
'Jambagh',
'Jamia Osmania ',
'Jangammet',
'Jeedimetla',
'Jeedimetla Industrial Area',
'JNTU',
'Journalist Colony',
'Jubilee Hills',
'Jubilee Hills Road No 1',
'Jubilee Hills Road No 10',
'Jubilee Hills Road No 11',
'Jubilee Hills Road No 12',
'Jubilee Hills Road No 13',
'Jubilee Hills Road No 14',
'Jubilee Hills Road No 15',
'Jubilee Hills Road No 16',
'Jubilee Hills Road No 17',
'Jubilee Hills Road No 18',
'Jubilee Hills Road No 19',
'Jubilee Hills Road No 2',
'Jubilee Hills Road No 20',
'Jubilee Hills Road No 21',
'Jubilee Hills Road No 22',
'Jubilee Hills Road No 23',
'Jubilee Hills Road No 24',
'Jubilee Hills Road No 25',
'Jubilee Hills Road No 26',
'Jubilee Hills Road No 27',
'Jubilee Hills Road No 28',
'Jubilee Hills Road No 29',
'Jubilee Hills Road No 3',
'Jubilee Hills Road No 30',
'Jubilee Hills Road No 31',
'Jubilee Hills Road No 32',
'Jubilee Hills Road No 33',
'Jubilee Hills Road No 34',
'Jubilee Hills Road No 35',
'Jubilee Hills Road No 36',
'Jubilee Hills Road No 37',
'Jubilee Hills Road No 38',
'Jubilee Hills Road No 39',
'Jubilee Hills Road No 4',
'Jubilee Hills Road No 40',
'Jubilee Hills Road No 41',
'Jubilee Hills Road No 42',
'Jubilee Hills Road No 43',
'Jubilee Hills Road No 44',
'Jubilee Hills Road No 45',
'Jubilee Hills Road No 46',
'Jubilee Hills Road No 47',
'Jubilee Hills Road No 48',
'Jubilee Hills Road No 49',
'Jubilee Hills Road No 5',
'Jubilee Hills Road No 50',
'Jubilee Hills Road No 51',
'Jubilee Hills Road No 52',
'Jubilee Hills Road No 53',
'Jubilee Hills Road No 54',
'Jubilee Hills Road No 55',
'Jubilee Hills Road No 56',
'Jubilee Hills Road No 57',
'Jubilee Hills Road No 58',
'Jubilee Hills Road No 59',
'Jubilee Hills Road No 6',
'Jubilee Hills Road No 60',
'Jubilee Hills Road No 61',
'Jubilee Hills Road No 62',
'Jubilee Hills Road No 63',
'Jubilee Hills Road No 64',
'Jubilee Hills Road No 65',
'Jubilee Hills Road No 66',
'Jubilee Hills Road No 67',
'Jubilee Hills Road No 68',
'Jubilee Hills Road No 69',
'Jubilee Hills Road No 7',
'Jubilee Hills Road No 70',
'Jubilee Hills Road No 71',
'Jubilee Hills Road No 72',
'Jubilee Hills Road No 73',
'Jubilee Hills Road No 74',
'Jubilee Hills Road No 75',
'Jubilee Hills Road No 76',
'Jubilee Hills Road No 77',
'Jubilee Hills Road No 78',
'Jubilee Hills Road No 79',
'Jubilee Hills Road No 8',
'Jubilee Hills Road No 80',
'Jubilee Hills Road No 81',
'Jubilee Hills Road No 82',
'Jubilee Hills Road No 83',
'Jubilee Hills Road No 84',
'Jubilee Hills Road No 85',
'Jubilee Hills Road No 86',
'Jubilee Hills Road No 87',
'Jubilee Hills Road No 88',
'Jubilee Hills Road No 89',
'Jubilee Hills Road No 9',
'Jubilee Hills Road No 90',
'Jubilee Hills Road No 91',
'Jubilee Hills Road No 92',
'Kachiguda',
'Kachiguda Railway Station',
'Kakatiyanagar',
'Kali Mandir',
'Kalyan Nagar Colony',
'Kamatipura',
'Kampinibagh',
'Kanchanbagh',
'Kapra',
'Karimnagar',
'Karkhana',
'Karmanghat',
'Karwan',
'Kavadiguda',
'Kaykur',
'Keshavagiri',
'Khairtabad',
'Khaja Guda',
'Khilwat',
'Kishanbagh',
'Kondapur',
'Kothaguda',
'Kothapet',
'Koti',
'KPHB Colony',
'Kukatpally',
'Kundan Bagh',
'Kurmaguda',
'Kushaiguda',
'L.B. Nagar',
'Lakdi-Ka-Pool',
'Lal Darwaza',
'Lalapet',
'Lalithabagh',
'Langer House',
'Lifestyle, Begumpet',
'Lingampally',
'Macha Bollaram',
'Madhapur',
'Madina',
'Madinaguda',
'Mahabubnagar',
'Maheshwaram',
'Malakpet',
'Malaysian Township',
'Malkajgiri',
'Mallapur',
'Mallepally',
'Manghalhat',
'Manikonda',
'Mansoorabad',
'Marapuguda',
'Marredpally',
'Masab Tank',
'Medak',
'Meerpet',
'Mehdipatnam',
'Mettuguda',
'Minister Road',
'Miyapur',
'Moghalpura',
'Moosapet',
'Moosarambagh',
'Mothinagar',
'Moula Ali',
'Mount Opera',
'Mozampura',
'Muradnagar',
'Musheerabad',
'Mushirabad',
'Mylardevpally',
'Nacharam',
'Nagole',
'Nalgonda',
'Nallagutta',
'Nallakunta',
'Namal Gundu',
'Nampally',
'Nampally Railway Station',
'Nanalnagar',
'Nandanarnagar',
'Narayanguda',
'Nawabsaheb Kunta',
'Necklace Road',
'Neredmet',
'New Malakpet',
'New Saidabad Colony',
'Nizamabad',
'Nizampet',
'Noorkhan Bazar',
'NTR Nagar',
'Old Bowenpally',
'Old Malakpet',
'Old Malkajgiri',
'Osmania University',
'P&T Colony',
'Padmarao Nagar',
'Padmashali Colony',
'Panjagutta',
'Paradise Cricle',
'Parsigutta',
'Parvati Nagar',
'Patancheruvu',
'Patel Nagar',
'Pathergatti',
'Pedda Kamalagiri',
'Pragathi Nagar',
'Prakasham Nagar',
'Pratapnagar',
'Premavatipet',
'Prenderghast Road',
'Puranapool',
'Putli Bowli',
'Qutubullapur',
'Rahamath Nagar',
'Rain Bazar',
'Raj Bhavan Road',
'Rajendra Nagar',
'Rajiv Gandhi Nagar',
'Rama Chandra Puram',
'Rama Krishna Puram',
'Ramanthapur',
'Ramgopal pet',
'Ramnagar',
'Ramnaspura',
'Ramoji Film City',
'Ranigunj',
'Ravindranagar Colony',
'Red Hills',
'Regimental Bazar',
'Riyasat Nagar',
'S.D. Road',
'S.P. Road',
'S.R. Nagar',
'Safilguda',
'Sai Colony',
'Sai Nagar Colony',
'Saidabad Colony',
'Saifabad',
'Sainikpuri',
'Saleem Nagar',
'Sanathnagar',
'Sanghi Temple',
'Santoshnagar',
'Saroor Nagar',
'Secreteriat',
'Secunderabad',
'Secunderabad Railway Station',
'Seethaphalmandi',
'Serilingampally',
'Shaikpet',
'Shali Banda',
'Shameerpet',
'Shamshabad Airport',
'Shamshabad Village',
'Shankerpally',
'Shapur Nagar',
'Shilpa Park',
'Shivarampally',
'Shrinagar Colony',
'Siddiambar Bazar',
'Sikh village',
'Sindhi Colony',
'Sitaphal Mandi',
'Sitarampet',
'Sneha Nagar colony',
'Somajiguda',
'Srinagar Colony',
'Srinivasanagar',
'Subhashnagar',
'Sultan Bazar',
'Suraram Colony',
'Survey Colony',
'Talabchanchalam',
'Tank Bund',
'Tarbund',
'Tarnaka',
'Tellapur',
'Tilak Nagar',
'Tolichowki',
'Trimulgherry',
'Tukaram Gate',
'Umanagar',
'Umda Bazar',
'Uppal',
'Uppuguda',
'Vaidiknagar',
'Vansathalipuram',
'Vemana Colony',
'Vengalrao Nagar',
'Venkatapuram',
'Vidyanagar',
'Vijayanagar Colony',
'Vijayapuri',
'Vishwasnagar',
'Vittal Rao Nagar',
'Vivekananda Nagar Colony',
'Warangal',
'Warasiguda',
'West Marredpally',
'Whitefields',
'Whitehouse, Begumpet',
'Yapral',
'Yousufguda',
'Ziaguda'
]}


APP_CITIES = ["Hyderabad"]