APP_LOCATIONS = ['Abids',
'Airport',
'Amberpet',
'Banjara Hills',
'Begumpet',
'Bolarum' ,
'Bus Station',
'Dilsukhnagar',
'Habsiguda',
'Himayat Nagar',
'Hitech City',
'Jamia Osmania',
'Jeedimetla Industrial Area',
'Jubilee Hills',
'Kachiguda Railway Station',
'Karimnagar',
'Keshavagiri',
'Lal Darwaza',
'Langar House',
'Mahabubnagar',
'Marredpally',
'Medak',
'Mehdipatnam',
'Mushirabad',
'Nalgonda',
'Nampally',
'Nampally Railway Station',
'Nizamabad',
'NTR Nagar',
'Prakasham Nagar',
'Punjagutta',
'Sanathnagar',
'Secunderabad Railway Station',
'Tarnaka',
'Trimulgherry',
'Umda Bazar',
'Warangal',
'Kavadiguda',
'Marapuguda',
'Padmashali Colony',
'Umanagar',
'Sindhi Colony',
'Nallagutta',
'Begum Bazar',
'Siddiambar Bazar',
'Padmashali Colony',
'Gaddi Annaram',
'Kalyan Nagar Colony',
'New Saidabad Colony',
'Maheshwaram Lines',
'Kottapet',
'Barkas',
'Patel Nagar',
'Gaulipura',
'Bhavani Nagar',
'Premavatipet',
'Pratapnagar',
'Kamatipura',
'Devibagh',
'Khilwat',
'Survey Colony',
'Tilak Nagar',
'Srinivasanagar',
'Kakatiyanagar',
'Sneha Nagar colony',
'Ravindranagar Colony',
'Budha Nagar',
'Warisguda',
'Namal Gundu',
'Vijayapuri',
'Lalapet',
'Putli Bowli',
'Sitarampet',
'Chakanwad',
'Koti',
'Domalguda',
'Sultan Bazar',
'Saifabad',
'Lakdi-Ka-Pool',
'Mozampura',
'Somajiguda',
'Errammanzil',
'Shrinagar Colony',
'Huda Colony',
'Madhapur',
'Parvati Nagar',
'Journalist Colony',
'Venkatapuram',
'Vithalraonagar',
'Balaji Nagar',
'Kampinibagh',
'Rajiv Gandhi Nagar',
'Santoshnagar',
'Vishwasnagar',
'Muradnagar',
'Indirammanagar',
'Anandnagar Colony',
'Tarbund',
'Kaykur',
'Alwal',
'Sai Colony',
'Jairamnagar',
'Ayodhyanagar',
'Chintala',
'Vaidiknagar',
'Nandanarnagar',
'Subhashnagar',
'Fatehnagar',
'Erragadda',
'Balkampet',
'Banjara Nagar',
'Pedda Kamalagiri'
]
