development:
  adapter: mysql2
  database: pool_ride_development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: pool_ride_test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: pool_ride_production
  username: root
  password:
  host: localhost


