development:
  adapter: mysql
  database: pool_ride_development
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  database: pool_ride_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: pool_ride_production
  username: root
  password:
  host: localhost


